### ISSUE TITLE
When clicking on the extension icon, nothing happens

### ISSUE THREAD

**Issue by 7valkio** [timothywashburn/badapple#1]
I tried installing the extension but when I press on the extension icon, it only outputs `bad apple started` again and then `Program already injected`
![Screenshot 2024-04-07 132423](https://github.com/timothywashburn/badapple/assets/113270877/5ec14d48-cec1-4bb7-9d53-e75eaeb1460e)

**Comment by 7valkio** [comment]
It seems I just had to refresh the page and click on the "Contribution settings" to see the toggle which didn't show up earlier for some reason, my bad! 😄

**Comment by timothywashburn** [comment]
Sorry yeah I ended up changing the way that the program starts to the dropdown menu over just running on click. I didn't get around to making a readme maybe I'll do that now.
